# This is the default config file, you can override it by creating a config.yaml in the same directory
# by default, all linters are enabled if you don't specify.

qbox/kodo: # github repository name, which will override the settings in qbox org
  staticcheck: # repo specific settings will override the settings in qbox org
    enable: true
    workDir: "src/qiniu.com/kodo"
    command: staticcheck
    args: ["./..."]
    run_if_changed: ["src/qiniu.com/kodo/.*\\.go$"] # only run if changed files match the regex

qbox/gaea-admin:
  staticcheck:
    enable: true
    args: ["-debug.no-compile-errors=true", "./..."]